### ISSUE TITLE
Gitbook do repositório

### ISSUE THREAD

**Issue by ghost** [BeeTech-global/bee-stylish#3]
Porque não transformar esse cara em um [Gitbook](http://gitbook.io/)? Talvez fique melhor para manter e a grande vantagem é que vocês ganham uma página web da documentação desse cara no githubpages. =)

**Comment by airroom** [comment]
Poxa, Edmo, você ÉDMAIS. Vamos fazer essa zueirinha siim :3

**Comment by ghost** [comment]
HAHAHA <3 
Não seja por isso [Proposal Gitbook #4](https://github.com/BeeTech-global/bee-stylish/pull/4)

Só tem que dar uma arrumada nos textos pra deixar mais bonitinho na página inicial.
E também fazer um esqueminha pra publicar no build direto no github-pages hehehe talvez colocar no CI pra fazer isso sei lá hahahaha

**Comment by airroom** [comment]
Demorou! Vou bizoiar logo mais. o @mrprompt pode ajudar no "ROBOCOP" do build  (diz que sim, Big James)

**Comment by mrprompt** [comment]
Bóóóóra!!!!

**Comment by mrprompt** [comment]
Do carai a idéia @edmolima, to completamente fissurado na ferramenta, obrigado por apresentar.

**Comment by ghost** [comment]
@mrprompt boa mano, espero que até dê pra aproveitar em workflow de projetos mesmos de bibliotecas e tal. Assim fica mais fácil manter e tal =) é nós manos!
