### ISSUE TITLE
Diretório _book não deve ser versionado

### ISSUE THREAD

**Issue by mrprompt** [BeeTech-global/bee-stylish#7]
O diretório *_book* é gerado pelo build do gitbook, ele deve ficar no .gitignore

**Comment by airroom** [comment]
Tem que fazer um esqueminha para este cara ir na branch `gh-pages` hmm

**Comment by mrprompt** [comment]
tá no forno :)

**Comment by airroom** [comment]
É TUPÃ NO CÉU E BIG JAMES NO GITHUB <3

**Comment by mrprompt** [comment]
ahahahahahaha <3
